### ISSUE TITLE
Allow setting a TTL for hcp_vault_cluster_admin_token resource

### ISSUE THREAD

**Issue by SpootyMcSpoot** [hashicorp/terraform-provider-hcp#235] opened 2021-12-13 21:03 UTC
### Description

If we use hcp_vault_cluster_admin_token in terraform plan it generates a token with 6h TTL. This token is not tracked in state meaning every plan will create a token which goes against the user license. We would like to be able to set a TTL for this token through the terraform config say 5mins in order for these to die off quickly and not count against our license.
### New or Affected Resource(s)

* hcp_XXXXX

### Potential Terraform Configuration

```hcl
resource "hcp_vault_cluster_admin_token" "primary" {
  count = var.tf_plan_flag == "false" ? 1 : 0
  cluster_id = hcp_vault_cluster.primary.cluster_id
  ttl = 5m <------- new config option here


  depends_on = [
    hcp_vault_cluster.primary
  ]
}
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bcmdarroch** [comment] 2021-12-14 19:35
Thanks for submitting this issue! I'll submit this to our Vault team and see what we can do!

**Comment by iiro** [comment] 2022-04-09 08:08
Hi @bcmdarroch! :) Any updates on this yet...? It's been a while since the latest :)

**Comment by bcmdarroch** [comment] 2022-08-23 22:28
Apologies for the delayed response! We're following up with Vault team.

**Comment by bcmdarroch** [comment] 2022-11-17 22:57
Closing this issue with the following guidance from our official Vault docs. The admin token has a limited TTL by design, since it is not intended as a long-term auth method. If you continue to run into problems, please let us know in a new issue.

> A good practice is to limit the use of the admin token and configure your preferred auth method(s) for regular use. The auth methods you choose to enable will be based on the who (person) or what (machine) will access your HCP Vault cluster. It is not uncommon to have multiple auth methods enabled.
source: https://developer.hashicorp.com/vault/tutorials/cloud-ops/hcp-vault-namespace-considerations#hcp-vault-admin-namespace

The [Manage Authentication Methods](https://developer.hashicorp.com/vault/tutorials/cloud/vault-auth-method) guide walks through how to set up proper authentication once your cluster has been bootstrapped with the admin token.

**Closed by bcmdarroch** 2022-11-17 22:57 UTC
Labels: enhancement
